workflow file changed

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -9,8 +9,18 @@ jobs:
         steps:
             - name: Say Hello
               run: echo "Say Hello"  
+    
+    echo-hello:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Say Hello
+              run: echo "Hello World"
     echo-goodbye:
         runs-on: ubuntu-latest
         steps:
+            - name: Failed Step
+              run: |
+                echo "This step will fail"
+                exit 1
             - name: Say Goodbye
-              run: echo "Say Goodbye"
+              run: echo "Goodbye!"
